# Generated by Django 3.1.7 on 2021-05-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210522_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ispaid',
            new_name='isPaid',
        ),
    ]
